### PR TITLE
Swipe Refresh functionality added in Archive Activity

### LINKED ISSUE #129: Add SwipeRefreshLayout in Archives Section.
Refer to this. ( https://velmm.com/swiperefreshlayout-example/ )

### PR DESCRIPTION
**Pull request by yk1ax**
Added the functionality and checked it by running with disabling the default handler in the onCreate and refreshing it
This closes #129 
@refactor-droidyy tell me if some more modifications are needed in this

ezgif com-video-to-gif (2)

### CODE REVIEW

**Comment by refactor-droidyy** [comment]
@yk1ax use different branch for different PR.Attach gif for the changes made.

**Comment by yk1ax** [comment]
@refractor-droidyy So should I first close this PR and then make another one in a new branch with just the change asked for in #129

**Comment by refactor-droidyy** [comment]
@yk1ax that's fine for now but for the upcoming PR always use a new branch as if any code change is suggested it can be changed separately.
Try to not to use a master branch instead create a branch out of it for PRs as if something is gone wrong u can easily delete the current branch and again make a clone from the master one and you are good to go.
Also, attach the gif for the changes established.

**Comment by yk1ax** [comment]
@refactor-droidyy Understood and GIF added

**Comment by refactor-droidyy** [comment]
@yk1ax Good work 👍 squash your commit.

**Comment by yk1ax** [comment]
> @yk1ax Good work 👍 squash your commit.

@refactor-droidyy Done

**Pull request merged**
