### PR TITLE
Add getsetfoss site to the navigation drawer

### LINKED ISSUE #11: Add getsetfoss site to the navigation drawer
Add getsetfoss site to the navigation drawer menu 

To know more about Navigation drawer Check [this](https://www.journaldev.com/9958/android-navigation-drawer-example-tutorial)

- *Multiple people can work at the same time, first one to get the PR merged will be awarded the points*

### PR DESCRIPTION
**Pull request by Retarded-Ape**
fix #11

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Attach a GIF showing UI changes and working of the new feature

**Comment by Retarded-Ape** [comment]
ezgif com-video-to-gif

**Comment by GOVINDDIXIT** [comment]
Good Work! Just fix PR title and description and this can be merged

**Comment by Retarded-Ape** [comment]
Done!!

**Pull request merged**
