### PR TITLE
code redundancy reduced

### LINKED ISSUE #135: Some code redundancy in the onChangeTab function in TimeTableActivity.java
@refactor-droidyy The change that I intend to make removes almost 30 extra lines of code

### PR DESCRIPTION
**Pull request by yk1ax**
This closes #135 
@refactor-droidyy this is the change I initially intended to make but I have one more idea, using the TextViews of tabs of different days within an array so that they can be accessed by index which would make the code very much shorter and simpler using loops. Would doing this be considered as obfuscation of the code ?

### CODE REVIEW

**Comment by refactor-droidyy** [comment]
Attach gif reflection the Ui changes.

**Comment by refactor-droidyy** [comment]
I don't think using array of textviews can reduce the code since each time u have to set the text size and there would be only a slight change ... Instead of tue. you will use are[2].set.... .

**Comment by yk1ax** [comment]
> I don't think using array of textviews can reduce the code since each time u have to set the text size and there would be only a slight change ... Instead of tue. you will use are[2].set.... .

currently i first assigned default values to all five values and then in the switch case depending on the value of position corresponding changes were made.
By using the array I can assign the default values in a loop with 5 iterations and the just write a just 2 lines like:
Day[position].setTextSize(28);
Day[position].getResources().getColor(R.color.bright);

**Comment by refactor-droidyy** [comment]
@yk1ax to what you are thinking is also a way to do this job but this change is not required as it will reduce the number of lines of code inside the loop but you will have to explicitly set the corresponding ids. Attach a gif reflecting UI changes made.

**Comment by yk1ax** [comment]
@refactor-droidyy This didn't have any UI changes it functions exactly the same as before

**Pull request merged**
