### PR TITLE
Add profile picture of complete faculty staff

### LINKED ISSUE #10: Add profile picture of complete faculty staff
Add a folder containing profile picture of complete faculty staff

The final folder should look like [this](https://github.com/GOVINDDIXIT/IIITA-Student-App/tree/master/faculty/photos)

### PR DESCRIPTION
**Pull request by Retarded-Ape**
fix #10

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
Why you are closing the old PR you have to make changes in the same PR. These things count. From now onwards, do changes in the same PR.

**Comment by Retarded-Ape** [comment]
I have not made these commits on Git but directly on the forked Repo and then made a PR.
I am not sure how to squash commits made directly from GitHub.
Should I make a new PR using Git

**Comment by GOVINDDIXIT** [comment]
Everything is possible in the same PR, closing and opening new PRs for same issues is a bad practice. Your goal is to have a single commit per PR. Hint is Squashing the commits to one.
I have shared a tutorial above regarding squashing check that.

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Use git bash from now onwards

**Pull request merged**
