### PR TITLE
Add DSC Site

### LINKED ISSUE #41: Add DSC site
Add DSC IIITL site in the navigation menu and remove "Albums"
Site Link: https://dsciiitl.netlify.com/

### PR DESCRIPTION
**Pull request by Retarded-Ape**
Fix #41

### CODE REVIEW

**Comment by Retarded-Ape** [comment]
DSC

**Comment by Retarded-Ape** [comment]
Done Sir!!!

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Update the GIF

**Comment by Retarded-Ape** [comment]
On the way

**Comment by Retarded-Ape** [comment]
DSC111

**Pull request merged**
